mediawiki-config-path: ../mediawiki-config
tableschema-files:
  - whitelisted.yaml
  - greylisted.yaml
user-dbname-regex: '(p|u|s)\d{4,5}.*'
hosts:
  - labsdb1001.eqiad.wmnet
  - labsdb1002.eqiad.wmnet
  - labsdb1003.eqiad.wmnet
